export const CHANGE_SINGER_ARTISTS = "singer/CHANGE_SINGER_ARTISTS";
export const CHANGE_SINGER_SONGS = "singer/CHANGE_SINGER_SONGS";
export const CHANGE_SINGER_ENTER_LOADING = "singer/CHANGE_SINGER_ENTER_LOADING"