export const CHANGE_CATEGORY = "singers/CHANGE_CATEGORY";
export const CHANGE_SINGER_LIST = "singers/CHANGE_SINGER_LIST";
export const CHANGE_ALPHA = "singers/CHANGE_ALPHA";
export const CHANGE_LIST_OFFSET = "singers/CHANGE_LIST_OFFSET";
export const CHANGE_ENTER_LOADING = "singers/CHANGE_ENTER_LOADING";
export const CHANGE_PULLUP_LOADING = "singers/CHANGE_PULLUP_LOADING";
export const CHANGE_PULLDOWN_LOADING = "singers/CHANGE_PULLDOWN_LOADING"